(module
	(import "env" "memory" (memory 1000))
	(import "env" "table" (table 1000 externref))
	(import "env" "decode" (func $decode (param i32) (result externref)))
	(import "env" "encode" (func $encode (param externref)))
	(import "env" "arrayNew" (func $arrayNew (param i32) (result externref)))
	(import "env" "arrayGet" (func $arrayGet (param externref i32) (result externref)))
	(import "env" "arraySet" (func $arrayPush (param externref i32 externref)))
	(func (export "encodeJs") (param $length i32)
		(local $index i32)
		(call $encode (table.get (i32.const 0)))
		(loop $loop
			(i32.store
				(i32.mul (local.get $index) (i32.const 4))
				(local.get $index)
			)
			(local.set $index (i32.add (local.get $index) (i32.const 1)))
			(br_if $loop (i32.lt_u (local.get $index) (local.get $length)))
		)
	)
	(func (export "decodeJs") (param $length i32)
		(table.set (i32.const 0) (call $decode (local.get $length)))
	)
	(func (export "encodeWasm") (param $length i32)
		(local $array externref)
		(local $index i32)
		(local.set $array (table.get (i32.const 0)))
		(loop $loop
			(table.set (local.get $index) (call $arrayGet (local.get $array) (local.get $index)))
			(i32.store
				(i32.mul (local.get $index) (i32.const 4))
				(local.get $index)
			)
			(local.set $index (i32.add (local.get $index) (i32.const 1)))
			(br_if $loop (i32.lt_u (local.get $index) (local.get $length)))
		)
	)
	(func (export "decodeWasm") (param $length i32)
		(local $array externref)
		(local $index i32)
		(local.set $array (call $arrayNew (local.get $length)))
		(loop $loop
			(call $arrayPush
				(local.get $array)
				(local.get $index)
				(table.get (i32.load (i32.mul (local.get $index) (i32.const 4))))
			)
			(local.set $index (i32.add (local.get $index) (i32.const 1)))
			(br_if $loop (i32.lt_u (local.get $index) (local.get $length)))
		)
		(table.set (i32.const 0) (local.get $array))
	)
)
