name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install wasm-tools
        uses: bytecodealliance/actions/wasm-tools/setup@v1

      - name: Make `dist` Directory
        run: mkdir -p dist

      - name: Copy index.html to `dist` Directory
        run: cp index.html dist/index.html

      - name: Compile WAT to Wasm
        run: wasm-tools parse test.wat -o dist/test.wasm

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
